version: '2.3'
services:
  elastic:
    image: elasticsearch:7.6.2
    network_mode: host
    environment: ['discovery.type=single-node', 'logger.level=error']
    healthcheck:
      interval: 5s
      retries: 500
      test: curl localhost:9200
    ## uncomment the next line when deploying in production
    #restart: always

  kosh:
    image: cceh/kosh:latest
    network_mode: host
    command: ['--data_host', 'localhost:9200']
    healthcheck:
      interval: 5s
      retries: 500
      test: wget -q localhost:5000 2>&1 | grep -q HTTP
    depends_on:
      elastic:
        condition: service_healthy
    ## uncomment the next line when deploying in production
    #restart: always
