version: '2.3'
services:
  elastic:
    image: elasticsearch:7.6.2
    networks: ['network']
    environment: ['discovery.type=single-node', 'logger.level=error']
    healthcheck:
      interval: 5s
      retries: 500
      test: curl localhost:9200
    ## uncomment the next line when deploying in production
    #restart: always

  kosh:
    image: cceh/kosh:latest
    command: ['--data_host', 'elastic']
    ## the first value is the port used by the host and the second by docker internally
    ports: ['5000:5000']
    networks: ['network']
    healthcheck:
      interval: 5s
      retries: 500
      test: wget -q localhost:5000 2>&1 | grep -q HTTP
    depends_on:
      elastic:
        condition: service_healthy
    ## uncomment the next line when deploying in production
    #restart: always
networks:
  network:
    driver: bridge
