version: '2.3'

services:
  elastic:
    ## Uncomment the next line when the host network should be used.
    # network_mode: host

    ## Comment 'restart: "no"' and uncomment 'restart: always' when deploying in production.
    restart: "no"
    # restart: always

  kosh:
    ## Uncomment the next line when the host network should be used.
    # network_mode: host

    ## Uncomment the next line when deploying in production
    # restart: always

    ## volumes:
    ##   - PATH_TO_KOSH_INI_FILE:/etc/kosh.ini:ro
    ##   - PATH_TO_XML_LEXICAL_DATA_WITH_KOSH_FILES:/var/lib/kosh:ro
    volumes:
      - ./kosh.ini:/etc/kosh.ini:ro
      - ../kosh_data/hoenig:/var/lib/kosh:ro

    command: ['--config_file', '/etc/kosh.ini']
